// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szatpjifuigjvusduvej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6YXRwamlmdWlnanZ1c2R1dmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTMzNzMsImV4cCI6MjA2NjIyOTM3M30.4K2YTd5qiIURkmrQyIN9jax_Y1iU9FTTIeSnrvDSEug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);